- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Ensure fail2ban service is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Deploy custom sshd_config
  template:
    src: sshd.config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart ssh

- name: Disable password auth for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    backup: yes
