- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default site config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Deploy webapp site config
  template:
    src: webapp.conf.j2
    dest: /etc/nginx/sites-available/webapp.conf
    owner: root
    group: root
    mode: "0644"

- name: Create symlink
  file:
    src: /etc/nginx/sites-available/webapp.conf
    dest: /etc/nginx/sites-enabled/webapp.conf
    state: link

- name: Get index.html from git (bonus point)
  get_url:
    url: "https://github.com/UURadekP/inizio_webpattern/blob/6bd68ce12099c3e62b9d3be765501ba971dfa140/index.html.j2"
    dest: "/tmp/index.html.j2"
    mode: "0644"
  become: yes

- name: Generate index.html from downloaded j2 template
  template:
    src: "/tmp/index.html.j2"
    dest: "/opt/static-sites/index.html"
    mode: "0644"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
  notify: Reload nginx

- name: nginx process check
  service:
    name: nginx
    state: started
    enabled: yes
