- hosts: all
  become: yes
  vars_files:
    - ~/inizio_test/ansible_inizio/group_vars/all.yml
  roles:
    - user
    - common
    - nginx
    - firewall
    - fail2ban

  tasks:
    - name: Validate HTTP service is running
      uri:
        url: "http://localhost:{{ nginx_port }}/"
        return_content: yes
      register: http_response

    - name: Check if web page contains correct content
      assert:
        that:
          - "'Welcome to the website' in http_response.content"
